# Merge upstream Moodle stable branch into moodle/testdev
name: Merge upstream

# Schedule
on:
  schedule:
      - cron: '11 11 * * 0'
  push:
    branches: [ moodle/testdev ]

jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Merge upstream
        run: |
          git status
          git checkout moodle/testdev
          git config user.name "Tansel T"
          git config user.email "tanselt@gmail.com"
          git pull https://github.com/moodle/moodle.git MOODLE_39_STABLE --no-edit
          git push origin moodle/testdev

